# Generated by Django 4.2.7 on 2023-12-14 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home', models.CharField(blank=True, max_length=50, null=True)),
                ('away', models.CharField(blank=True, max_length=50, null=True)),
                ('home_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('away_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('home_win', models.CharField(blank=True, max_length=50, null=True)),
                ('draw', models.CharField(blank=True, max_length=50, null=True)),
                ('away_win', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
