# Generated by Django 4.2.7 on 2023-12-16 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_fixture_away_score_fixture_draw_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fixture',
            old_name='home_win_status',
            new_name='away_status',
        ),
        migrations.AddField(
            model_name='fixture',
            name='home_status',
            field=models.CharField(blank=True, choices=[('up', 'up'), ('down', 'down')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='away_win',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
