# Generated by Django 4.2.7 on 2023-12-25 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_rename_home_win_status_fixture_away_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_balance',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
