# Generated by Django 4.2.7 on 2024-01-14 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0006_user_account_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_balance',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
