# Generated by Django 4.2.7 on 2024-01-26 00:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0007_alter_user_account_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='BetHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stake_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('predicted_outcome', models.CharField(blank=True, max_length=50, null=True)),
                ('actual_outcome', models.CharField(blank=True, max_length=50, null=True)),
                ('fixture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.fixture')),
            ],
        ),
        migrations.CreateModel(
            name='StakeAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stake_amount_max', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BetSlip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_stake_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_payout', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_winner', models.BooleanField(default=False)),
                ('bet_histories', models.ManyToManyField(related_name='bet_slips', to='server.bethistory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
