# Generated by Django 4.2.7 on 2024-01-28 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0008_bethistory_stakeamount_betslip'),
    ]

    operations = [
        migrations.AddField(
            model_name='betslip',
            name='slipID',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
