# Generated by Django 4.2.7 on 2024-01-29 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0009_betslip_slipid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='betslip',
            name='slipID',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
