# Generated by Django 4.2.7 on 2024-01-29 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0010_alter_betslip_slipid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_withdraw',
            field=models.BooleanField(default=False),
        ),
    ]
