# Generated by Django 4.2.7 on 2024-01-30 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0011_user_can_withdraw'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='can_withdraw',
            field=models.BooleanField(default=True),
        ),
    ]
