# Generated by Django 4.2.7 on 2024-01-31 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0012_alter_user_can_withdraw'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(blank=True, max_length=50, null=True)),
                ('lastName', models.CharField(blank=True, max_length=50, null=True)),
                ('phoneNumber', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('message', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='fixture',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='league',
            field=models.CharField(blank=True, choices=[('PL', 'Premier League'), ('LL', 'La Liga'), ('BL', 'BundesLiga'), ('SA', 'Serie A'), ('L1', 'Legue 1'), ('UCL', 'UEFA Champions League'), ('UEL', 'UEFA Europa League'), ('CLG', 'Classified Game')], max_length=3, null=True),
        ),
    ]
