# Generated by Django 4.2.7 on 2024-01-31 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0013_contactform_fixture_is_finished_alter_fixture_league'),
    ]

    operations = [
        migrations.AddField(
            model_name='betslip',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
