# Generated by Django 4.2.7 on 2024-02-01 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0015_betslip_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='betslip',
            name='is_combo',
            field=models.BooleanField(default=False),
        ),
    ]
