# Generated by Django 4.2.7 on 2024-02-07 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0017_alter_user_can_withdraw'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='deposit_amount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
