# Generated by Django 4.2.7 on 2024-03-05 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0018_user_deposit_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='show_withdraw_message',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='withdraw_message_eng',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='withdraw_message_fr',
            field=models.TextField(blank=True, null=True),
        ),
    ]
