# Generated by Django 4.2.7 on 2024-03-24 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0019_user_show_withdraw_message_user_withdraw_message_eng_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixture',
            name='can_bet',
            field=models.BooleanField(default=True),
        ),
    ]
