# Generated by Django 4.2.7 on 2024-03-25 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0020_fixture_can_bet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phoneNumber', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('amount', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_method', models.CharField(blank=True, choices=[('MTN', 'Mobile Money (MTN)'), ('OM', 'Orange Money (OM)')], max_length=5, null=True)),
            ],
        ),
    ]
