# Generated by Django 4.2.7 on 2024-04-15 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0023_user_withdrawal_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='stake_limit',
            field=models.IntegerField(blank=True, default=2000000, null=True),
        ),
    ]
