# Generated by Django 4.2.7 on 2024-07-25 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0024_user_stake_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixture',
            name='stake_limit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='league',
            field=models.CharField(blank=True, choices=[('UEC', 'UEFA European Championship'), ('CA', 'Copa America'), ('PL', 'Premier League'), ('LL', 'La Liga'), ('BL', 'BundesLiga'), ('SA', 'Serie A'), ('L1', 'Legue 1'), ('UCL', 'UEFA Champions League'), ('UEL', 'UEFA Europa League'), ('CLG', 'Classified Game')], max_length=3, null=True),
        ),
    ]
