# Generated by Django 4.2.7 on 2024-09-13 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0025_fixture_stake_limit_alter_fixture_league'),
    ]

    operations = [
        migrations.CreateModel(
            name='BetFixture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stake_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('predicted_outcome', models.CharField(blank=True, max_length=50, null=True)),
                ('actual_outcome', models.CharField(blank=True, max_length=50, null=True)),
                ('bet_slip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bet_fixtures', to='server.betslip')),
                ('fixture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.fixture')),
            ],
        ),
    ]
