# Generated by Django 4.2.7 on 2024-09-26 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0027_alter_betslip_bet_histories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='betslip',
            name='bet_histories',
            field=models.ManyToManyField(blank=True, related_name='bet_slips', to='server.bethistory'),
        ),
    ]
